### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by jeremiahgreer** [Leone25/zanichelli-downloader#30]
I am receiving the following error when trying to download an unencrypted book:

Processing...
(node:1359) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
file:///home/rebekah/kitaboo/kitaboo-downloader-main/index.js:60
        let title = content.package.metadata[0]["dc:title"][0];
                                    ^

TypeError: Cannot read properties of undefined (reading 'metadata')
    at file:///home/rebekah/kitaboo/kitaboo-downloader-main/index.js:60:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.0.0

Any suggestions on how to get past this issue?

Thanks!!

**Comment by jeremiahgreer** [comment]
I figured out the issue on my own.  I did not realize the URL was hard coded in the index.js.  My book had part of the URL that is different than how it was hard coded.  I edited the index.js to correct the URL and everything worked perfectly.

**Comment by Leone25** [comment]
could you share more info please? maybe we can implement a patch for it

**Comment by Lordam1927** [comment]
Sorry, it gives me the same error too, I just don't understand how to solve it (I have no expertise in the matter) could you explain better?

**Comment by Lordam1927** [comment]
I tried with another older book and it works, and I noticed that the URL is different.
The working one is like this:
https://webreader.zanichelli.it/ID/html5/ID/OPS/content.opf
the book I would like to download instead has the URL in the form:
https://webreader.zanichelli.it/ID/fixed_epub_image/ID/OEBPS/content.opf
What changes should I make to the index file to make it readable??

**Comment by jeremiahgreer** [comment]
@Leone25 the source code has I believe 4 references to the URL https://webreader.zanichelli.it..etc.. that are hardcoded.  As @Lordam1927 mentioned my book had an alternative URL that did not fit the exact pattern that was hard coded.   As a workaround, I just edited all the hardcoded URLs in the script to make it work. Maybe it would be better to have the script ask the user for the full URL path to the content.opf instead of just the ebookID?

**Comment by Lordam1927** [comment]
Hi, I'm continuing to try to download the pdf of my book, and in addition to the error in the URL which I corrected manually, being different, I noticed that it still didn't work, I realized that in fact in this book in particular a Unlike others, the items are written in this form here:
<item id="F23-3.xhtml" href="Text/F23-3.xhtml" media-type="application/xhtml+xml"/>
instead of .svg it therefore appears in .xhtml; I really don't know how to solve it.
Unfortunately the book is very new and evidently they have started to use another language.

**Comment by PieceOfCrazy** [comment]
@Lordam1927 I'm having the same issue, the new edition of the book came out this year and apparently they started using a new format, but I barely know what is going on and have no idea how this could be fixed
