### ISSUE TITLE
 Errori su booktab

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/zanichelli-downloader#42]
ciao
penso sia solo per i libri booktab (su kitaboo, al momento, non ho ricevuto errori)

primo errore (me lo da su 5 libri diversi): Non-whitespace before first tag.
![Cattura](https://github.com/user-attachments/assets/7115dbf3-481b-43b4-ae92-7448d8db1eff)

secondo errore:  Cannot read properties of undefined (reading '0')
![Cattura](https://github.com/user-attachments/assets/4c4f6e2e-299c-489c-939c-b456c831c168)

**Comment by Leone25** [comment]
i've tried the script with the books i have access to and it still works.

please dm me on twitter (same name + 03), so that i can assist you further

**Comment by sefirothmorpheus** [comment]
posso ancora contattarti per questi problemi dei libri?

**Comment by Leone25** [comment]
si
