### ISSUE TITLE
Logged in as: undefined undefined (Account Google)

### ISSUE THREAD

**Issue by lui-gig** [Leone25/zanichelli-downloader#45]
Ciao, Ho lo stesso problema visto in un altro thread, Il mio caso però è che accedo al sito Zanichelli con l'account di Google. C'è differenza con un account creato sul sito?

**Comment by Leone25** [comment]
si, non si può accedere con account esterni, è necessario impostare una password, dovrebbe bastare fare un reset della password e seguire la procedura e poi riprovare
